server = 'coregdanskdbserver.database.windows.net'
database = 'MITeam'
username = 'add_user'
password = 'add_pwd'
driver = '{ODBC Driver 17 for SQL Server}'
search_strings_file = 'path\\search_strings.txt'
